### ISSUE TITLE
Error adding entities for domain sensor with platform aps_api_client since 2023.8.0

### ISSUE THREAD

**Issue by Id2ndR** [n0liver/HAAC#1]
I created the issue https://github.com/home-assistant/core/issues/98789 but it may be related to the code of this integration.

**Comment by n0liver** [comment]
Thanks, it was indeed something to fix in this integration. Works fine now on my 2023.8.2 installation :+1:

**Comment by Id2ndR** [comment]
I saw the change in *device_info* function in commit 79d00cd.

Thank you for this very useful integration!
